# Generated by Django 5.0.1 on 2024-03-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0005_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='county',
        ),
    ]
