# Generated by Django 5.0.1 on 2024-03-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0007_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SokoApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Potatoes', 'Potatoes'), ('Cereals', 'Cereals'), ('Onions', 'Onions'), ('Spices', 'Spices'), ('Birds', 'Birds'), ('Animals', 'Animals'), ('Feeds', 'Feeds'), ('Seedlings', 'Seedlings'), ('Farm Inputs', 'Farm Inputs'), ('Farm Machinery', 'Farm Machinery')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
