# Generated by Django 5.0.3 on 2024-03-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0008_product_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Potatoes', 'Potaoes'), ('Cereals', 'Cereals'), ('Onions', 'Onions'), ('Spices', 'Spices'), ('Birds', 'Birds'), ('Animals', 'Animals'), ('Feeds', 'Feeds'), ('Seedlings', 'Seedlings'), ('Farm Inputs', 'Farm Inputs'), ('Farm Machinery', 'Farm Machinery')], max_length=50),
        ),
    ]
