# Generated by Django 5.0.1 on 2024-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Potatoes', 'Potatoes'), ('Cereals', 'Cereals'), ('Onions', 'Onions'), ('Spices', 'Spices'), ('Birds', 'Birds & Products'), ('Animals', 'Animals & Products'), ('Feeds', 'Feeds'), ('Seedlings', 'Seedlings'), ('Farm Inputs', 'Farm Inputs'), ('Farm Machinery', 'Farm Machinery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
