# Generated by Django 5.0.1 on 2024-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0012_delete_mymodel_alter_product_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Cereals & Grains', 'Cereals & Grains'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Potatoes', 'Potatoes'), ('Onions', 'Onions'), ('Spices', 'Spices'), ('Birds & Products', 'Birds & Products'), ('Animals & Products', 'Animals & Products'), ('Seedlings', 'Seedlings'), ('Farm Inputs', 'Farm Inputs'), ('Farm Machinery', 'Farm Machinery')], max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=50)),
                ('location', models.CharField(max_length=255)),
                ('timeframe', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('additional_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
            ],
        ),
    ]
