# Generated by Django 5.0.1 on 2024-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0015_alter_exports_category_products_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
