# Generated by Django 5.0.1 on 2024-03-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0017_alter_exports_image1_alter_exports_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='category_products',
        ),
    ]
