# Generated by Django 5.0.1 on 2024-03-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0018_remove_offers_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
