# Generated by Django 5.0.3 on 2024-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0022_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Fisheries', 'Fisheries'), ('Cereals & Grains', 'Cereals & Grains'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Potatoes', 'Potatoes'), ('Onions', 'Onions'), ('Spices', 'Spices'), ('Birds & Products', 'Birds & Products'), ('Animals & Products', 'Animals & Products'), ('Seedlings', 'Seedlings'), ('Farm Inputs', 'Farm Inputs'), ('Farm Machinery', 'Farm Machinery')], max_length=100),
        ),
    ]
