# Generated by Django 5.0.3 on 2024-06-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SokoApp', '0026_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Complaint', 'Complaint'), ('Complement', 'Complement'), ('Refund', 'Refund')], max_length=100),
        ),
    ]
